package com.example.demo.order.model;
// Generated 1 Mar, 2021 1:11:43 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Revinfo generated by hbm2java
 */
@Entity
@Table(name = "revinfo", catalog = "crmord")
public class Revinfo implements java.io.Serializable {

	private Integer rev;
	private Long revtstmp;

	public Revinfo() {
	}

	public Revinfo(Long revtstmp) {
		this.revtstmp = revtstmp;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "REV", unique = true, nullable = false)
	public Integer getRev() {
		return this.rev;
	}

	public void setRev(Integer rev) {
		this.rev = rev;
	}

	@Column(name = "REVTSTMP")
	public Long getRevtstmp() {
		return this.revtstmp;
	}

	public void setRevtstmp(Long revtstmp) {
		this.revtstmp = revtstmp;
	}

}
