package com.example.demo.order.model;
// Generated 1 Mar, 2021 1:11:43 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblChangeReq generated by hbm2java
 */
@Entity
@Table(name = "tbl_change_req", catalog = "crmord")
public class TblChangeReq implements java.io.Serializable {

	private long recordId;
	private Long orderId;
	private String code;
	private String status;
	private String reqType;
	private String reqReason;
	private Date reqExecuteDate;
	private Date reqActualExecuteDate;
	private Date expComplDate;
	private String errMsg;
	private String createProleType;
	private Long createProleId;
	private String createProleName;
	private String createProleCode;
	private Date createTime;
	private String modifyProleType;
	private Long modifyProleId;
	private String modifyProleName;
	private String modifyProleCode;
	private Date modifyTime;

	public TblChangeReq() {
	}

	public TblChangeReq(long recordId) {
		this.recordId = recordId;
	}

	public TblChangeReq(long recordId, Long orderId, String code, String status, String reqType, String reqReason,
			Date reqExecuteDate, Date reqActualExecuteDate, Date expComplDate, String errMsg, String createProleType,
			Long createProleId, String createProleName, String createProleCode, Date createTime, String modifyProleType,
			Long modifyProleId, String modifyProleName, String modifyProleCode, Date modifyTime) {
		this.recordId = recordId;
		this.orderId = orderId;
		this.code = code;
		this.status = status;
		this.reqType = reqType;
		this.reqReason = reqReason;
		this.reqExecuteDate = reqExecuteDate;
		this.reqActualExecuteDate = reqActualExecuteDate;
		this.expComplDate = expComplDate;
		this.errMsg = errMsg;
		this.createProleType = createProleType;
		this.createProleId = createProleId;
		this.createProleName = createProleName;
		this.createProleCode = createProleCode;
		this.createTime = createTime;
		this.modifyProleType = modifyProleType;
		this.modifyProleId = modifyProleId;
		this.modifyProleName = modifyProleName;
		this.modifyProleCode = modifyProleCode;
		this.modifyTime = modifyTime;
	}

	@Id

	@Column(name = "record_id", unique = true, nullable = false)
	public long getRecordId() {
		return this.recordId;
	}

	public void setRecordId(long recordId) {
		this.recordId = recordId;
	}

	@Column(name = "order_id")
	public Long getOrderId() {
		return this.orderId;
	}

	public void setOrderId(Long orderId) {
		this.orderId = orderId;
	}

	@Column(name = "code", length = 64)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "status", length = 32)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "req_type", length = 32)
	public String getReqType() {
		return this.reqType;
	}

	public void setReqType(String reqType) {
		this.reqType = reqType;
	}

	@Column(name = "req_reason", length = 4000)
	public String getReqReason() {
		return this.reqReason;
	}

	public void setReqReason(String reqReason) {
		this.reqReason = reqReason;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "req_execute_date", length = 19)
	public Date getReqExecuteDate() {
		return this.reqExecuteDate;
	}

	public void setReqExecuteDate(Date reqExecuteDate) {
		this.reqExecuteDate = reqExecuteDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "req_actual_execute_date", length = 19)
	public Date getReqActualExecuteDate() {
		return this.reqActualExecuteDate;
	}

	public void setReqActualExecuteDate(Date reqActualExecuteDate) {
		this.reqActualExecuteDate = reqActualExecuteDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "exp_compl_date", length = 19)
	public Date getExpComplDate() {
		return this.expComplDate;
	}

	public void setExpComplDate(Date expComplDate) {
		this.expComplDate = expComplDate;
	}

	@Column(name = "err_msg", length = 4000)
	public String getErrMsg() {
		return this.errMsg;
	}

	public void setErrMsg(String errMsg) {
		this.errMsg = errMsg;
	}

	@Column(name = "create_prole_type", length = 12)
	public String getCreateProleType() {
		return this.createProleType;
	}

	public void setCreateProleType(String createProleType) {
		this.createProleType = createProleType;
	}

	@Column(name = "create_prole_id")
	public Long getCreateProleId() {
		return this.createProleId;
	}

	public void setCreateProleId(Long createProleId) {
		this.createProleId = createProleId;
	}

	@Column(name = "create_prole_name", length = 64)
	public String getCreateProleName() {
		return this.createProleName;
	}

	public void setCreateProleName(String createProleName) {
		this.createProleName = createProleName;
	}

	@Column(name = "create_prole_code", length = 64)
	public String getCreateProleCode() {
		return this.createProleCode;
	}

	public void setCreateProleCode(String createProleCode) {
		this.createProleCode = createProleCode;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "modify_prole_type", length = 12)
	public String getModifyProleType() {
		return this.modifyProleType;
	}

	public void setModifyProleType(String modifyProleType) {
		this.modifyProleType = modifyProleType;
	}

	@Column(name = "modify_prole_id")
	public Long getModifyProleId() {
		return this.modifyProleId;
	}

	public void setModifyProleId(Long modifyProleId) {
		this.modifyProleId = modifyProleId;
	}

	@Column(name = "modify_prole_name", length = 64)
	public String getModifyProleName() {
		return this.modifyProleName;
	}

	public void setModifyProleName(String modifyProleName) {
		this.modifyProleName = modifyProleName;
	}

	@Column(name = "modify_prole_code", length = 64)
	public String getModifyProleCode() {
		return this.modifyProleCode;
	}

	public void setModifyProleCode(String modifyProleCode) {
		this.modifyProleCode = modifyProleCode;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modify_time", length = 19)
	public Date getModifyTime() {
		return this.modifyTime;
	}

	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}

}
