package com.example.demo.order.model;
// Generated 1 Mar, 2021 1:11:43 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblChangeReqDtlRsc generated by hbm2java
 */
@Entity
@Table(name = "tbl_change_req_dtl_rsc", catalog = "crmord")
public class TblChangeReqDtlRsc implements java.io.Serializable {

	private long recordId;
	private Long changeReqId;
	private Long changeReqDtlId;
	private Long orderId;
	private Long orderItemId;
	private Long orderItemRscId;
	private String actionInd;
	private String rscType;
	private String reserveRef;
	private String rscDtl;
	private String status;
	private Long refTxnId;
	private String createProleType;
	private Long createProleId;
	private String createProleName;
	private String createProleCode;
	private Date createTime;
	private String modifyProleType;
	private Long modifyProleId;
	private String modifyProleName;
	private String modifyProleCode;
	private Date modifyTime;

	public TblChangeReqDtlRsc() {
	}

	public TblChangeReqDtlRsc(long recordId) {
		this.recordId = recordId;
	}

	public TblChangeReqDtlRsc(long recordId, Long changeReqId, Long changeReqDtlId, Long orderId, Long orderItemId,
			Long orderItemRscId, String actionInd, String rscType, String reserveRef, String rscDtl, String status,
			Long refTxnId, String createProleType, Long createProleId, String createProleName, String createProleCode,
			Date createTime, String modifyProleType, Long modifyProleId, String modifyProleName, String modifyProleCode,
			Date modifyTime) {
		this.recordId = recordId;
		this.changeReqId = changeReqId;
		this.changeReqDtlId = changeReqDtlId;
		this.orderId = orderId;
		this.orderItemId = orderItemId;
		this.orderItemRscId = orderItemRscId;
		this.actionInd = actionInd;
		this.rscType = rscType;
		this.reserveRef = reserveRef;
		this.rscDtl = rscDtl;
		this.status = status;
		this.refTxnId = refTxnId;
		this.createProleType = createProleType;
		this.createProleId = createProleId;
		this.createProleName = createProleName;
		this.createProleCode = createProleCode;
		this.createTime = createTime;
		this.modifyProleType = modifyProleType;
		this.modifyProleId = modifyProleId;
		this.modifyProleName = modifyProleName;
		this.modifyProleCode = modifyProleCode;
		this.modifyTime = modifyTime;
	}

	@Id

	@Column(name = "record_id", unique = true, nullable = false)
	public long getRecordId() {
		return this.recordId;
	}

	public void setRecordId(long recordId) {
		this.recordId = recordId;
	}

	@Column(name = "change_req_id")
	public Long getChangeReqId() {
		return this.changeReqId;
	}

	public void setChangeReqId(Long changeReqId) {
		this.changeReqId = changeReqId;
	}

	@Column(name = "change_req_dtl_id")
	public Long getChangeReqDtlId() {
		return this.changeReqDtlId;
	}

	public void setChangeReqDtlId(Long changeReqDtlId) {
		this.changeReqDtlId = changeReqDtlId;
	}

	@Column(name = "order_id")
	public Long getOrderId() {
		return this.orderId;
	}

	public void setOrderId(Long orderId) {
		this.orderId = orderId;
	}

	@Column(name = "order_item_id")
	public Long getOrderItemId() {
		return this.orderItemId;
	}

	public void setOrderItemId(Long orderItemId) {
		this.orderItemId = orderItemId;
	}

	@Column(name = "order_item_rsc_id")
	public Long getOrderItemRscId() {
		return this.orderItemRscId;
	}

	public void setOrderItemRscId(Long orderItemRscId) {
		this.orderItemRscId = orderItemRscId;
	}

	@Column(name = "action_ind", length = 12)
	public String getActionInd() {
		return this.actionInd;
	}

	public void setActionInd(String actionInd) {
		this.actionInd = actionInd;
	}

	@Column(name = "rsc_type", length = 32)
	public String getRscType() {
		return this.rscType;
	}

	public void setRscType(String rscType) {
		this.rscType = rscType;
	}

	@Column(name = "reserve_ref", length = 32)
	public String getReserveRef() {
		return this.reserveRef;
	}

	public void setReserveRef(String reserveRef) {
		this.reserveRef = reserveRef;
	}

	@Column(name = "rsc_dtl")
	public String getRscDtl() {
		return this.rscDtl;
	}

	public void setRscDtl(String rscDtl) {
		this.rscDtl = rscDtl;
	}

	@Column(name = "status", length = 32)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "ref_txn_id")
	public Long getRefTxnId() {
		return this.refTxnId;
	}

	public void setRefTxnId(Long refTxnId) {
		this.refTxnId = refTxnId;
	}

	@Column(name = "create_prole_type", length = 12)
	public String getCreateProleType() {
		return this.createProleType;
	}

	public void setCreateProleType(String createProleType) {
		this.createProleType = createProleType;
	}

	@Column(name = "create_prole_id")
	public Long getCreateProleId() {
		return this.createProleId;
	}

	public void setCreateProleId(Long createProleId) {
		this.createProleId = createProleId;
	}

	@Column(name = "create_prole_name", length = 64)
	public String getCreateProleName() {
		return this.createProleName;
	}

	public void setCreateProleName(String createProleName) {
		this.createProleName = createProleName;
	}

	@Column(name = "create_prole_code", length = 64)
	public String getCreateProleCode() {
		return this.createProleCode;
	}

	public void setCreateProleCode(String createProleCode) {
		this.createProleCode = createProleCode;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "modify_prole_type", length = 12)
	public String getModifyProleType() {
		return this.modifyProleType;
	}

	public void setModifyProleType(String modifyProleType) {
		this.modifyProleType = modifyProleType;
	}

	@Column(name = "modify_prole_id")
	public Long getModifyProleId() {
		return this.modifyProleId;
	}

	public void setModifyProleId(Long modifyProleId) {
		this.modifyProleId = modifyProleId;
	}

	@Column(name = "modify_prole_name", length = 64)
	public String getModifyProleName() {
		return this.modifyProleName;
	}

	public void setModifyProleName(String modifyProleName) {
		this.modifyProleName = modifyProleName;
	}

	@Column(name = "modify_prole_code", length = 64)
	public String getModifyProleCode() {
		return this.modifyProleCode;
	}

	public void setModifyProleCode(String modifyProleCode) {
		this.modifyProleCode = modifyProleCode;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modify_time", length = 19)
	public Date getModifyTime() {
		return this.modifyTime;
	}

	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}

}
