package com.example.demo.order.model;
// Generated 1 Mar, 2021 1:11:43 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblFulfillOrder generated by hbm2java
 */
@Entity
@Table(name = "tbl_fulfill_order", catalog = "crmord")
public class TblFulfillOrder implements java.io.Serializable {

	private long recordId;
	private TblFulfillOrder tblFulfillOrder;
	private String type;
	private Long orderId;
	private String triggerBy;
	private String actionType;
	private String status;
	private String latestRtnRefId;
	private Long dependOnForderId;
	private String dependType;
	private String dependRtnCode;
	private Date complDate;
	private Date requestExecuteTime;
	private String reachedPonr;
	private String code;
	private String referenceCode;
	private String createProleType;
	private Long createProleId;
	private String createProleName;
	private String createProleCode;
	private Date createTime;
	private String modifyProleType;
	private Long modifyProleId;
	private String modifyProleName;
	private String modifyProleCode;
	private Date modifyTime;
	private Long mainOrderItemId;
	private Long processFailCount;
	private String content;
	private Set<TblOrderItemForderAssgn> tblOrderItemForderAssgns = new HashSet(0);
	private Set<TblFulfillOrderProp> tblFulfillOrderProps = new HashSet<TblFulfillOrderProp>(0);
	private Set<TblFulfillOrderReq> tblFulfillOrderReqs = new HashSet<TblFulfillOrderReq>(0);
	private Set<TblFulfillOrder> tblFulfillOrders = new HashSet<TblFulfillOrder>(0);

	public TblFulfillOrder() {
	}

	public TblFulfillOrder(long recordId) {
		this.recordId = recordId;
	}

	public TblFulfillOrder(long recordId, TblFulfillOrder tblFulfillOrder, String type, Long orderId, String triggerBy,
			String actionType, String status, String latestRtnRefId, Long dependOnForderId, String dependType,
			String dependRtnCode, Date complDate, Date requestExecuteTime, String reachedPonr, String code,
			String referenceCode, String createProleType, Long createProleId, String createProleName,
			String createProleCode, Date createTime, String modifyProleType, Long modifyProleId, String modifyProleName,
			String modifyProleCode, Date modifyTime, Long mainOrderItemId, Long processFailCount, String content,
			Set<TblOrderItemForderAssgn> tblOrderItemForderAssgns, Set<TblFulfillOrderProp> tblFulfillOrderProps, Set<TblFulfillOrderReq> tblFulfillOrderReqs, Set<TblFulfillOrder> tblFulfillOrders) {
		this.recordId = recordId;
		this.tblFulfillOrder = tblFulfillOrder;
		this.type = type;
		this.orderId = orderId;
		this.triggerBy = triggerBy;
		this.actionType = actionType;
		this.status = status;
		this.latestRtnRefId = latestRtnRefId;
		this.dependOnForderId = dependOnForderId;
		this.dependType = dependType;
		this.dependRtnCode = dependRtnCode;
		this.complDate = complDate;
		this.requestExecuteTime = requestExecuteTime;
		this.reachedPonr = reachedPonr;
		this.code = code;
		this.referenceCode = referenceCode;
		this.createProleType = createProleType;
		this.createProleId = createProleId;
		this.createProleName = createProleName;
		this.createProleCode = createProleCode;
		this.createTime = createTime;
		this.modifyProleType = modifyProleType;
		this.modifyProleId = modifyProleId;
		this.modifyProleName = modifyProleName;
		this.modifyProleCode = modifyProleCode;
		this.modifyTime = modifyTime;
		this.mainOrderItemId = mainOrderItemId;
		this.processFailCount = processFailCount;
		this.content = content;
		this.tblOrderItemForderAssgns = tblOrderItemForderAssgns;
		this.tblFulfillOrderProps = tblFulfillOrderProps;
		this.tblFulfillOrderReqs = tblFulfillOrderReqs;
		this.tblFulfillOrders = tblFulfillOrders;
	}

	@Id

	@Column(name = "record_id", unique = true, nullable = false)
	public long getRecordId() {
		return this.recordId;
	}

	public void setRecordId(long recordId) {
		this.recordId = recordId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "p_fulfill_order_id")
	public TblFulfillOrder getTblFulfillOrder() {
		return this.tblFulfillOrder;
	}

	public void setTblFulfillOrder(TblFulfillOrder tblFulfillOrder) {
		this.tblFulfillOrder = tblFulfillOrder;
	}

	@Column(name = "type", length = 32)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "order_id")
	public Long getOrderId() {
		return this.orderId;
	}

	public void setOrderId(Long orderId) {
		this.orderId = orderId;
	}

	@Column(name = "trigger_by", length = 32)
	public String getTriggerBy() {
		return this.triggerBy;
	}

	public void setTriggerBy(String triggerBy) {
		this.triggerBy = triggerBy;
	}

	@Column(name = "action_type", length = 32)
	public String getActionType() {
		return this.actionType;
	}

	public void setActionType(String actionType) {
		this.actionType = actionType;
	}

	@Column(name = "status", length = 32)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "latest_rtn_ref_id", length = 32)
	public String getLatestRtnRefId() {
		return this.latestRtnRefId;
	}

	public void setLatestRtnRefId(String latestRtnRefId) {
		this.latestRtnRefId = latestRtnRefId;
	}

	@Column(name = "depend_on_forder_id")
	public Long getDependOnForderId() {
		return this.dependOnForderId;
	}

	public void setDependOnForderId(Long dependOnForderId) {
		this.dependOnForderId = dependOnForderId;
	}

	@Column(name = "depend_type", length = 32)
	public String getDependType() {
		return this.dependType;
	}

	public void setDependType(String dependType) {
		this.dependType = dependType;
	}

	@Column(name = "depend_rtn_code", length = 32)
	public String getDependRtnCode() {
		return this.dependRtnCode;
	}

	public void setDependRtnCode(String dependRtnCode) {
		this.dependRtnCode = dependRtnCode;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "compl_date", length = 19)
	public Date getComplDate() {
		return this.complDate;
	}

	public void setComplDate(Date complDate) {
		this.complDate = complDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "request_execute_time", length = 19)
	public Date getRequestExecuteTime() {
		return this.requestExecuteTime;
	}

	public void setRequestExecuteTime(Date requestExecuteTime) {
		this.requestExecuteTime = requestExecuteTime;
	}

	@Column(name = "reached_ponr", length = 12)
	public String getReachedPonr() {
		return this.reachedPonr;
	}

	public void setReachedPonr(String reachedPonr) {
		this.reachedPonr = reachedPonr;
	}

	@Column(name = "code", length = 64)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "reference_code", length = 512)
	public String getReferenceCode() {
		return this.referenceCode;
	}

	public void setReferenceCode(String referenceCode) {
		this.referenceCode = referenceCode;
	}

	@Column(name = "create_prole_type", length = 12)
	public String getCreateProleType() {
		return this.createProleType;
	}

	public void setCreateProleType(String createProleType) {
		this.createProleType = createProleType;
	}

	@Column(name = "create_prole_id")
	public Long getCreateProleId() {
		return this.createProleId;
	}

	public void setCreateProleId(Long createProleId) {
		this.createProleId = createProleId;
	}

	@Column(name = "create_prole_name", length = 64)
	public String getCreateProleName() {
		return this.createProleName;
	}

	public void setCreateProleName(String createProleName) {
		this.createProleName = createProleName;
	}

	@Column(name = "create_prole_code", length = 64)
	public String getCreateProleCode() {
		return this.createProleCode;
	}

	public void setCreateProleCode(String createProleCode) {
		this.createProleCode = createProleCode;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "modify_prole_type", length = 12)
	public String getModifyProleType() {
		return this.modifyProleType;
	}

	public void setModifyProleType(String modifyProleType) {
		this.modifyProleType = modifyProleType;
	}

	@Column(name = "modify_prole_id")
	public Long getModifyProleId() {
		return this.modifyProleId;
	}

	public void setModifyProleId(Long modifyProleId) {
		this.modifyProleId = modifyProleId;
	}

	@Column(name = "modify_prole_name", length = 64)
	public String getModifyProleName() {
		return this.modifyProleName;
	}

	public void setModifyProleName(String modifyProleName) {
		this.modifyProleName = modifyProleName;
	}

	@Column(name = "modify_prole_code", length = 64)
	public String getModifyProleCode() {
		return this.modifyProleCode;
	}

	public void setModifyProleCode(String modifyProleCode) {
		this.modifyProleCode = modifyProleCode;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modify_time", length = 19)
	public Date getModifyTime() {
		return this.modifyTime;
	}

	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}

	@Column(name = "main_order_item_id")
	public Long getMainOrderItemId() {
		return this.mainOrderItemId;
	}

	public void setMainOrderItemId(Long mainOrderItemId) {
		this.mainOrderItemId = mainOrderItemId;
	}

	@Column(name = "process_fail_count")
	public Long getProcessFailCount() {
		return this.processFailCount;
	}

	public void setProcessFailCount(Long processFailCount) {
		this.processFailCount = processFailCount;
	}

	@Column(name = "content")
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblFulfillOrder")
	public Set<TblOrderItemForderAssgn> getTblOrderItemForderAssgns() {
		return this.tblOrderItemForderAssgns;
	}

	public void setTblOrderItemForderAssgns(Set<TblOrderItemForderAssgn> tblOrderItemForderAssgns) {
		this.tblOrderItemForderAssgns = tblOrderItemForderAssgns;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblFulfillOrder")
	public Set<TblFulfillOrderProp> getTblFulfillOrderProps() {
		return this.tblFulfillOrderProps;
	}

	public void setTblFulfillOrderProps(Set<TblFulfillOrderProp> tblFulfillOrderProps) {
		this.tblFulfillOrderProps = tblFulfillOrderProps;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblFulfillOrder")
	public Set<TblFulfillOrderReq> getTblFulfillOrderReqs() {
		return this.tblFulfillOrderReqs;
	}

	public void setTblFulfillOrderReqs(Set<TblFulfillOrderReq> tblFulfillOrderReqs) {
		this.tblFulfillOrderReqs = tblFulfillOrderReqs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblFulfillOrder")
	public Set<TblFulfillOrder> getTblFulfillOrders() {
		return this.tblFulfillOrders;
	}

	public void setTblFulfillOrders(Set<TblFulfillOrder> tblFulfillOrders) {
		this.tblFulfillOrders = tblFulfillOrders;
	}

}
