package com.example.demo.order.model;
// Generated 1 Mar, 2021 1:11:43 PM by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblOrderItemPriceAud generated by hbm2java
 */
@Entity
@Table(name = "tbl_order_item_price_aud", catalog = "crmord")
public class TblOrderItemPriceAud implements java.io.Serializable {

	private TblOrderItemPriceAudId id;
	private Byte revtype;
	private Long orderId;
	private Long orderItemId;
	private Long priceId;
	private String priceType;
	private String priceDesc;
	private Float priceValue;
	private String unit;
	private String taxRequired;
	private Float taxRate;
	private Float taxIncludedAmount;
	private Long altPriceRefId;
	private BigDecimal altPrice;
	private String actionType;
	private String markDelInd;
	private String billDesc;
	private Long applyToPriceId;
	private BigDecimal percentage;
	private BigDecimal chrgAmount;
	private BigDecimal duration;
	private String priceSubType;
	private String createProleType;
	private Long createProleId;
	private String createProleName;
	private String createProleCode;
	private Date createTime;
	private String modifyProleType;
	private Long modifyProleId;
	private String modifyProleName;
	private String modifyProleCode;
	private Date modifyTime;
	private String name;
	private String recurChrgPeriodType;
	private Float recurChrgPeriodLength;

	public TblOrderItemPriceAud() {
	}

	public TblOrderItemPriceAud(TblOrderItemPriceAudId id) {
		this.id = id;
	}

	public TblOrderItemPriceAud(TblOrderItemPriceAudId id, Byte revtype, Long orderId, Long orderItemId, Long priceId,
			String priceType, String priceDesc, Float priceValue, String unit, String taxRequired, Float taxRate,
			Float taxIncludedAmount, Long altPriceRefId, BigDecimal altPrice, String actionType, String markDelInd,
			String billDesc, Long applyToPriceId, BigDecimal percentage, BigDecimal chrgAmount, BigDecimal duration,
			String priceSubType, String createProleType, Long createProleId, String createProleName,
			String createProleCode, Date createTime, String modifyProleType, Long modifyProleId, String modifyProleName,
			String modifyProleCode, Date modifyTime, String name, String recurChrgPeriodType,
			Float recurChrgPeriodLength) {
		this.id = id;
		this.revtype = revtype;
		this.orderId = orderId;
		this.orderItemId = orderItemId;
		this.priceId = priceId;
		this.priceType = priceType;
		this.priceDesc = priceDesc;
		this.priceValue = priceValue;
		this.unit = unit;
		this.taxRequired = taxRequired;
		this.taxRate = taxRate;
		this.taxIncludedAmount = taxIncludedAmount;
		this.altPriceRefId = altPriceRefId;
		this.altPrice = altPrice;
		this.actionType = actionType;
		this.markDelInd = markDelInd;
		this.billDesc = billDesc;
		this.applyToPriceId = applyToPriceId;
		this.percentage = percentage;
		this.chrgAmount = chrgAmount;
		this.duration = duration;
		this.priceSubType = priceSubType;
		this.createProleType = createProleType;
		this.createProleId = createProleId;
		this.createProleName = createProleName;
		this.createProleCode = createProleCode;
		this.createTime = createTime;
		this.modifyProleType = modifyProleType;
		this.modifyProleId = modifyProleId;
		this.modifyProleName = modifyProleName;
		this.modifyProleCode = modifyProleCode;
		this.modifyTime = modifyTime;
		this.name = name;
		this.recurChrgPeriodType = recurChrgPeriodType;
		this.recurChrgPeriodLength = recurChrgPeriodLength;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "recordId", column = @Column(name = "record_id", nullable = false)),
			@AttributeOverride(name = "rev", column = @Column(name = "REV", nullable = false)) })
	public TblOrderItemPriceAudId getId() {
		return this.id;
	}

	public void setId(TblOrderItemPriceAudId id) {
		this.id = id;
	}

	@Column(name = "REVTYPE")
	public Byte getRevtype() {
		return this.revtype;
	}

	public void setRevtype(Byte revtype) {
		this.revtype = revtype;
	}

	@Column(name = "order_id")
	public Long getOrderId() {
		return this.orderId;
	}

	public void setOrderId(Long orderId) {
		this.orderId = orderId;
	}

	@Column(name = "order_item_id")
	public Long getOrderItemId() {
		return this.orderItemId;
	}

	public void setOrderItemId(Long orderItemId) {
		this.orderItemId = orderItemId;
	}

	@Column(name = "price_id")
	public Long getPriceId() {
		return this.priceId;
	}

	public void setPriceId(Long priceId) {
		this.priceId = priceId;
	}

	@Column(name = "price_type", length = 12)
	public String getPriceType() {
		return this.priceType;
	}

	public void setPriceType(String priceType) {
		this.priceType = priceType;
	}

	@Column(name = "price_desc", length = 4000)
	public String getPriceDesc() {
		return this.priceDesc;
	}

	public void setPriceDesc(String priceDesc) {
		this.priceDesc = priceDesc;
	}

	@Column(name = "price_value", precision = 20)
	public Float getPriceValue() {
		return this.priceValue;
	}

	public void setPriceValue(Float priceValue) {
		this.priceValue = priceValue;
	}

	@Column(name = "unit", length = 32)
	public String getUnit() {
		return this.unit;
	}

	public void setUnit(String unit) {
		this.unit = unit;
	}

	@Column(name = "tax_required", length = 12)
	public String getTaxRequired() {
		return this.taxRequired;
	}

	public void setTaxRequired(String taxRequired) {
		this.taxRequired = taxRequired;
	}

	@Column(name = "tax_rate", precision = 20)
	public Float getTaxRate() {
		return this.taxRate;
	}

	public void setTaxRate(Float taxRate) {
		this.taxRate = taxRate;
	}

	@Column(name = "tax_included_amount", precision = 20)
	public Float getTaxIncludedAmount() {
		return this.taxIncludedAmount;
	}

	public void setTaxIncludedAmount(Float taxIncludedAmount) {
		this.taxIncludedAmount = taxIncludedAmount;
	}

	@Column(name = "alt_price_ref_id")
	public Long getAltPriceRefId() {
		return this.altPriceRefId;
	}

	public void setAltPriceRefId(Long altPriceRefId) {
		this.altPriceRefId = altPriceRefId;
	}

	@Column(name = "alt_price", precision = 20)
	public BigDecimal getAltPrice() {
		return this.altPrice;
	}

	public void setAltPrice(BigDecimal altPrice) {
		this.altPrice = altPrice;
	}

	@Column(name = "action_type", length = 32)
	public String getActionType() {
		return this.actionType;
	}

	public void setActionType(String actionType) {
		this.actionType = actionType;
	}

	@Column(name = "mark_del_ind", length = 12)
	public String getMarkDelInd() {
		return this.markDelInd;
	}

	public void setMarkDelInd(String markDelInd) {
		this.markDelInd = markDelInd;
	}

	@Column(name = "bill_desc")
	public String getBillDesc() {
		return this.billDesc;
	}

	public void setBillDesc(String billDesc) {
		this.billDesc = billDesc;
	}

	@Column(name = "apply_to_price_id")
	public Long getApplyToPriceId() {
		return this.applyToPriceId;
	}

	public void setApplyToPriceId(Long applyToPriceId) {
		this.applyToPriceId = applyToPriceId;
	}

	@Column(name = "percentage", precision = 20)
	public BigDecimal getPercentage() {
		return this.percentage;
	}

	public void setPercentage(BigDecimal percentage) {
		this.percentage = percentage;
	}

	@Column(name = "chrg_amount", precision = 20)
	public BigDecimal getChrgAmount() {
		return this.chrgAmount;
	}

	public void setChrgAmount(BigDecimal chrgAmount) {
		this.chrgAmount = chrgAmount;
	}

	@Column(name = "duration", precision = 20)
	public BigDecimal getDuration() {
		return this.duration;
	}

	public void setDuration(BigDecimal duration) {
		this.duration = duration;
	}

	@Column(name = "price_sub_type", length = 32)
	public String getPriceSubType() {
		return this.priceSubType;
	}

	public void setPriceSubType(String priceSubType) {
		this.priceSubType = priceSubType;
	}

	@Column(name = "create_prole_type", length = 12)
	public String getCreateProleType() {
		return this.createProleType;
	}

	public void setCreateProleType(String createProleType) {
		this.createProleType = createProleType;
	}

	@Column(name = "create_prole_id")
	public Long getCreateProleId() {
		return this.createProleId;
	}

	public void setCreateProleId(Long createProleId) {
		this.createProleId = createProleId;
	}

	@Column(name = "create_prole_name", length = 64)
	public String getCreateProleName() {
		return this.createProleName;
	}

	public void setCreateProleName(String createProleName) {
		this.createProleName = createProleName;
	}

	@Column(name = "create_prole_code", length = 64)
	public String getCreateProleCode() {
		return this.createProleCode;
	}

	public void setCreateProleCode(String createProleCode) {
		this.createProleCode = createProleCode;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "modify_prole_type", length = 12)
	public String getModifyProleType() {
		return this.modifyProleType;
	}

	public void setModifyProleType(String modifyProleType) {
		this.modifyProleType = modifyProleType;
	}

	@Column(name = "modify_prole_id")
	public Long getModifyProleId() {
		return this.modifyProleId;
	}

	public void setModifyProleId(Long modifyProleId) {
		this.modifyProleId = modifyProleId;
	}

	@Column(name = "modify_prole_name", length = 64)
	public String getModifyProleName() {
		return this.modifyProleName;
	}

	public void setModifyProleName(String modifyProleName) {
		this.modifyProleName = modifyProleName;
	}

	@Column(name = "modify_prole_code", length = 64)
	public String getModifyProleCode() {
		return this.modifyProleCode;
	}

	public void setModifyProleCode(String modifyProleCode) {
		this.modifyProleCode = modifyProleCode;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modify_time", length = 19)
	public Date getModifyTime() {
		return this.modifyTime;
	}

	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}

	@Column(name = "name", length = 4000)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "recur_chrg_period_type", length = 32)
	public String getRecurChrgPeriodType() {
		return this.recurChrgPeriodType;
	}

	public void setRecurChrgPeriodType(String recurChrgPeriodType) {
		this.recurChrgPeriodType = recurChrgPeriodType;
	}

	@Column(name = "recur_chrg_period_length", precision = 8, scale = 0)
	public Float getRecurChrgPeriodLength() {
		return this.recurChrgPeriodLength;
	}

	public void setRecurChrgPeriodLength(Float recurChrgPeriodLength) {
		this.recurChrgPeriodLength = recurChrgPeriodLength;
	}

}
