package com.example.demo.order.model;
// Generated 1 Mar, 2021 1:11:43 PM by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblOrderItemTermPrice generated by hbm2java
 */
@Entity
@Table(name = "tbl_order_item_term_price", catalog = "crmord")
public class TblOrderItemTermPrice implements java.io.Serializable {

	private long recordId;
	private TblOrderItem tblOrderItem;
	private TblOrderItemTerm tblOrderItemTerm;
	private Long orderId;
	private Long priceId;
	private Long applyToPriceId;
	private String priceType;
	private String priceDesc;
	private String actionType;
	private String markDelInd;
	private String name;
	private BigDecimal percentage;
	private BigDecimal chrgAmt;
	private BigDecimal duration;
	private String billDesc;
	private String priceSubType;
	private String createProleType;
	private Long createProleId;
	private String createProleName;
	private String createProleCode;
	private Date createTime;
	private String modifyProleType;
	private Long modifyProleId;
	private String modifyProleName;
	private String modifyProleCode;
	private Date modifyTime;

	public TblOrderItemTermPrice() {
	}

	public TblOrderItemTermPrice(long recordId) {
		this.recordId = recordId;
	}

	public TblOrderItemTermPrice(long recordId, TblOrderItem tblOrderItem, TblOrderItemTerm tblOrderItemTerm,
			Long orderId, Long priceId, Long applyToPriceId, String priceType, String priceDesc, String actionType,
			String markDelInd, String name, BigDecimal percentage, BigDecimal chrgAmt, BigDecimal duration,
			String billDesc, String priceSubType, String createProleType, Long createProleId, String createProleName,
			String createProleCode, Date createTime, String modifyProleType, Long modifyProleId, String modifyProleName,
			String modifyProleCode, Date modifyTime) {
		this.recordId = recordId;
		this.tblOrderItem = tblOrderItem;
		this.tblOrderItemTerm = tblOrderItemTerm;
		this.orderId = orderId;
		this.priceId = priceId;
		this.applyToPriceId = applyToPriceId;
		this.priceType = priceType;
		this.priceDesc = priceDesc;
		this.actionType = actionType;
		this.markDelInd = markDelInd;
		this.name = name;
		this.percentage = percentage;
		this.chrgAmt = chrgAmt;
		this.duration = duration;
		this.billDesc = billDesc;
		this.priceSubType = priceSubType;
		this.createProleType = createProleType;
		this.createProleId = createProleId;
		this.createProleName = createProleName;
		this.createProleCode = createProleCode;
		this.createTime = createTime;
		this.modifyProleType = modifyProleType;
		this.modifyProleId = modifyProleId;
		this.modifyProleName = modifyProleName;
		this.modifyProleCode = modifyProleCode;
		this.modifyTime = modifyTime;
	}

	@Id

	@Column(name = "record_id", unique = true, nullable = false)
	public long getRecordId() {
		return this.recordId;
	}

	public void setRecordId(long recordId) {
		this.recordId = recordId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "order_item_id")
	public TblOrderItem getTblOrderItem() {
		return this.tblOrderItem;
	}

	public void setTblOrderItem(TblOrderItem tblOrderItem) {
		this.tblOrderItem = tblOrderItem;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "order_item_term_id")
	public TblOrderItemTerm getTblOrderItemTerm() {
		return this.tblOrderItemTerm;
	}

	public void setTblOrderItemTerm(TblOrderItemTerm tblOrderItemTerm) {
		this.tblOrderItemTerm = tblOrderItemTerm;
	}

	@Column(name = "order_id")
	public Long getOrderId() {
		return this.orderId;
	}

	public void setOrderId(Long orderId) {
		this.orderId = orderId;
	}

	@Column(name = "price_id")
	public Long getPriceId() {
		return this.priceId;
	}

	public void setPriceId(Long priceId) {
		this.priceId = priceId;
	}

	@Column(name = "apply_to_price_id")
	public Long getApplyToPriceId() {
		return this.applyToPriceId;
	}

	public void setApplyToPriceId(Long applyToPriceId) {
		this.applyToPriceId = applyToPriceId;
	}

	@Column(name = "price_type", length = 32)
	public String getPriceType() {
		return this.priceType;
	}

	public void setPriceType(String priceType) {
		this.priceType = priceType;
	}

	@Column(name = "price_desc", length = 4000)
	public String getPriceDesc() {
		return this.priceDesc;
	}

	public void setPriceDesc(String priceDesc) {
		this.priceDesc = priceDesc;
	}

	@Column(name = "action_type", length = 32)
	public String getActionType() {
		return this.actionType;
	}

	public void setActionType(String actionType) {
		this.actionType = actionType;
	}

	@Column(name = "mark_del_ind", length = 12)
	public String getMarkDelInd() {
		return this.markDelInd;
	}

	public void setMarkDelInd(String markDelInd) {
		this.markDelInd = markDelInd;
	}

	@Column(name = "name", length = 4000)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "percentage", precision = 20)
	public BigDecimal getPercentage() {
		return this.percentage;
	}

	public void setPercentage(BigDecimal percentage) {
		this.percentage = percentage;
	}

	@Column(name = "chrg_amt", precision = 20)
	public BigDecimal getChrgAmt() {
		return this.chrgAmt;
	}

	public void setChrgAmt(BigDecimal chrgAmt) {
		this.chrgAmt = chrgAmt;
	}

	@Column(name = "duration", precision = 20)
	public BigDecimal getDuration() {
		return this.duration;
	}

	public void setDuration(BigDecimal duration) {
		this.duration = duration;
	}

	@Column(name = "bill_desc", length = 4000)
	public String getBillDesc() {
		return this.billDesc;
	}

	public void setBillDesc(String billDesc) {
		this.billDesc = billDesc;
	}

	@Column(name = "price_sub_type", length = 32)
	public String getPriceSubType() {
		return this.priceSubType;
	}

	public void setPriceSubType(String priceSubType) {
		this.priceSubType = priceSubType;
	}

	@Column(name = "create_prole_type", length = 12)
	public String getCreateProleType() {
		return this.createProleType;
	}

	public void setCreateProleType(String createProleType) {
		this.createProleType = createProleType;
	}

	@Column(name = "create_prole_id")
	public Long getCreateProleId() {
		return this.createProleId;
	}

	public void setCreateProleId(Long createProleId) {
		this.createProleId = createProleId;
	}

	@Column(name = "create_prole_name", length = 64)
	public String getCreateProleName() {
		return this.createProleName;
	}

	public void setCreateProleName(String createProleName) {
		this.createProleName = createProleName;
	}

	@Column(name = "create_prole_code", length = 64)
	public String getCreateProleCode() {
		return this.createProleCode;
	}

	public void setCreateProleCode(String createProleCode) {
		this.createProleCode = createProleCode;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "modify_prole_type", length = 12)
	public String getModifyProleType() {
		return this.modifyProleType;
	}

	public void setModifyProleType(String modifyProleType) {
		this.modifyProleType = modifyProleType;
	}

	@Column(name = "modify_prole_id")
	public Long getModifyProleId() {
		return this.modifyProleId;
	}

	public void setModifyProleId(Long modifyProleId) {
		this.modifyProleId = modifyProleId;
	}

	@Column(name = "modify_prole_name", length = 64)
	public String getModifyProleName() {
		return this.modifyProleName;
	}

	public void setModifyProleName(String modifyProleName) {
		this.modifyProleName = modifyProleName;
	}

	@Column(name = "modify_prole_code", length = 64)
	public String getModifyProleCode() {
		return this.modifyProleCode;
	}

	public void setModifyProleCode(String modifyProleCode) {
		this.modifyProleCode = modifyProleCode;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modify_time", length = 19)
	public Date getModifyTime() {
		return this.modifyTime;
	}

	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}

}
