package com.example.demo.order.model;
// Generated 1 Mar, 2021 1:11:43 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblRscHist generated by hbm2java
 */
@Entity
@Table(name = "tbl_rsc_hist", catalog = "crmord")
public class TblRscHist implements java.io.Serializable {

	private long recordId;
	private String caller;
	private String txnCode;
	private String txnType;
	private String txnRefId;
	private String txnRefSys;
	private Date txnStartDate;
	private Date txnFinishDate;
	private String txnReqDtl;
	private String txnRespDtl;
	private String txnStatus;
	private String txnErrorMsg;
	private String refOrderType;
	private Long refOrderId;
	private String createProleType;
	private Long createProleId;
	private String createProleName;
	private String createProleCode;
	private Date createTime;
	private String modifyProleType;
	private Long modifyProleId;
	private String modifyProleName;
	private String modifyProleCode;
	private Date modifyTime;

	public TblRscHist() {
	}

	public TblRscHist(long recordId) {
		this.recordId = recordId;
	}

	public TblRscHist(long recordId, String caller, String txnCode, String txnType, String txnRefId, String txnRefSys,
			Date txnStartDate, Date txnFinishDate, String txnReqDtl, String txnRespDtl, String txnStatus,
			String txnErrorMsg, String refOrderType, Long refOrderId, String createProleType, Long createProleId,
			String createProleName, String createProleCode, Date createTime, String modifyProleType, Long modifyProleId,
			String modifyProleName, String modifyProleCode, Date modifyTime) {
		this.recordId = recordId;
		this.caller = caller;
		this.txnCode = txnCode;
		this.txnType = txnType;
		this.txnRefId = txnRefId;
		this.txnRefSys = txnRefSys;
		this.txnStartDate = txnStartDate;
		this.txnFinishDate = txnFinishDate;
		this.txnReqDtl = txnReqDtl;
		this.txnRespDtl = txnRespDtl;
		this.txnStatus = txnStatus;
		this.txnErrorMsg = txnErrorMsg;
		this.refOrderType = refOrderType;
		this.refOrderId = refOrderId;
		this.createProleType = createProleType;
		this.createProleId = createProleId;
		this.createProleName = createProleName;
		this.createProleCode = createProleCode;
		this.createTime = createTime;
		this.modifyProleType = modifyProleType;
		this.modifyProleId = modifyProleId;
		this.modifyProleName = modifyProleName;
		this.modifyProleCode = modifyProleCode;
		this.modifyTime = modifyTime;
	}

	@Id

	@Column(name = "record_id", unique = true, nullable = false)
	public long getRecordId() {
		return this.recordId;
	}

	public void setRecordId(long recordId) {
		this.recordId = recordId;
	}

	@Column(name = "caller", length = 50)
	public String getCaller() {
		return this.caller;
	}

	public void setCaller(String caller) {
		this.caller = caller;
	}

	@Column(name = "txn_code", length = 50)
	public String getTxnCode() {
		return this.txnCode;
	}

	public void setTxnCode(String txnCode) {
		this.txnCode = txnCode;
	}

	@Column(name = "txn_type", length = 50)
	public String getTxnType() {
		return this.txnType;
	}

	public void setTxnType(String txnType) {
		this.txnType = txnType;
	}

	@Column(name = "txn_ref_id", length = 50)
	public String getTxnRefId() {
		return this.txnRefId;
	}

	public void setTxnRefId(String txnRefId) {
		this.txnRefId = txnRefId;
	}

	@Column(name = "txn_ref_sys", length = 50)
	public String getTxnRefSys() {
		return this.txnRefSys;
	}

	public void setTxnRefSys(String txnRefSys) {
		this.txnRefSys = txnRefSys;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "txn_start_date", length = 19)
	public Date getTxnStartDate() {
		return this.txnStartDate;
	}

	public void setTxnStartDate(Date txnStartDate) {
		this.txnStartDate = txnStartDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "txn_finish_date", length = 19)
	public Date getTxnFinishDate() {
		return this.txnFinishDate;
	}

	public void setTxnFinishDate(Date txnFinishDate) {
		this.txnFinishDate = txnFinishDate;
	}

	@Column(name = "txn_req_dtl")
	public String getTxnReqDtl() {
		return this.txnReqDtl;
	}

	public void setTxnReqDtl(String txnReqDtl) {
		this.txnReqDtl = txnReqDtl;
	}

	@Column(name = "txn_resp_dtl")
	public String getTxnRespDtl() {
		return this.txnRespDtl;
	}

	public void setTxnRespDtl(String txnRespDtl) {
		this.txnRespDtl = txnRespDtl;
	}

	@Column(name = "txn_status", length = 50)
	public String getTxnStatus() {
		return this.txnStatus;
	}

	public void setTxnStatus(String txnStatus) {
		this.txnStatus = txnStatus;
	}

	@Column(name = "txn_error_msg", length = 4000)
	public String getTxnErrorMsg() {
		return this.txnErrorMsg;
	}

	public void setTxnErrorMsg(String txnErrorMsg) {
		this.txnErrorMsg = txnErrorMsg;
	}

	@Column(name = "ref_order_type", length = 50)
	public String getRefOrderType() {
		return this.refOrderType;
	}

	public void setRefOrderType(String refOrderType) {
		this.refOrderType = refOrderType;
	}

	@Column(name = "ref_order_id")
	public Long getRefOrderId() {
		return this.refOrderId;
	}

	public void setRefOrderId(Long refOrderId) {
		this.refOrderId = refOrderId;
	}

	@Column(name = "create_prole_type", length = 50)
	public String getCreateProleType() {
		return this.createProleType;
	}

	public void setCreateProleType(String createProleType) {
		this.createProleType = createProleType;
	}

	@Column(name = "create_prole_id")
	public Long getCreateProleId() {
		return this.createProleId;
	}

	public void setCreateProleId(Long createProleId) {
		this.createProleId = createProleId;
	}

	@Column(name = "create_prole_name", length = 64)
	public String getCreateProleName() {
		return this.createProleName;
	}

	public void setCreateProleName(String createProleName) {
		this.createProleName = createProleName;
	}

	@Column(name = "create_prole_code", length = 64)
	public String getCreateProleCode() {
		return this.createProleCode;
	}

	public void setCreateProleCode(String createProleCode) {
		this.createProleCode = createProleCode;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "modify_prole_type", length = 50)
	public String getModifyProleType() {
		return this.modifyProleType;
	}

	public void setModifyProleType(String modifyProleType) {
		this.modifyProleType = modifyProleType;
	}

	@Column(name = "modify_prole_id")
	public Long getModifyProleId() {
		return this.modifyProleId;
	}

	public void setModifyProleId(Long modifyProleId) {
		this.modifyProleId = modifyProleId;
	}

	@Column(name = "modify_prole_name", length = 64)
	public String getModifyProleName() {
		return this.modifyProleName;
	}

	public void setModifyProleName(String modifyProleName) {
		this.modifyProleName = modifyProleName;
	}

	@Column(name = "modify_prole_code", length = 64)
	public String getModifyProleCode() {
		return this.modifyProleCode;
	}

	public void setModifyProleCode(String modifyProleCode) {
		this.modifyProleCode = modifyProleCode;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modify_time", length = 19)
	public Date getModifyTime() {
		return this.modifyTime;
	}

	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}

}
