package com.example.demo.order.model;
// Generated 1 Mar, 2021 1:11:43 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * VwCreateSeq generated by hbm2java
 */
@Entity
@Table(name = "vw_create_seq", catalog = "crmord")
public class VwCreateSeq implements java.io.Serializable {

	private String nameExp1;

	public VwCreateSeq() {
	}

	public VwCreateSeq(String nameExp1) {
		this.nameExp1 = nameExp1;
	}

	@Id

	@Column(name = "Name_exp_1", length = 113)
	public String getNameExp1() {
		return this.nameExp1;
	}

	public void setNameExp1(String nameExp1) {
		this.nameExp1 = nameExp1;
	}

}
